[build]
  command = "npm run deploy"
  functions = "lambda" #  netlify-lambda reads this
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[redirects]]
  from = "http://dpf.nascar.com.pl/*"
  to = "https://nascar.com.pl/filtry/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dpf.nascar.com.pl/*"
  to = "https://nascar.com.pl/filtry/:splat"
  status = 301
  force = true
